basePath: /
consumes:
    - applications/json
info:
    description: '# Documentation for Product API'
    title: classification of Product API
    version: 1.0.0
paths: {}
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
